### PR TITLE
Update assets and add some design tweaks

### PR DESCRIPTION
**Pull request by equinusocio**
- [x] Update refresh icon to support retina display
- [x] Add some spaces and edit font-face:

screen shot 2016-05-03 at 23 26 37

### CODE REVIEW

**Comment by equinusocio** [comment]
@shahruz

**Comment by LoganDark2** [comment]
unistall isn't a word .-.

**Comment by equinusocio** [comment]
LoL

**Comment by LoganDark2** [comment]
LoL of the rings

**Comment by revelt** [comment]
But this is not the original repo! If you scroll top, it shows @shahruz forked it from @buzzfeed...
I think we're filing bugs on the wrong repo!

**Comment by equinusocio** [comment]
@revelt check the PR date and the latest commit on the original repo..

**Comment by revelt** [comment]
@equinusocio I'm very grateful for your and everybody's contributions on this fork. I do see that it's more alive then original. Anyway, I'm concerned because ideally there should be only one master repo where issues are tracked. It's especially important for this library because it's like Sublime Text's Package Manager - an essential thing. My existing plugins didn't sync with Toolbox and I'm still perplexed what to do about it.

**Comment by LoganDark** [comment]
@equinusocio wew

**Comment by equinusocio** [comment]
I'm switched to sketchpacks

**Pull request closed without merging**
